/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedBalanceVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBalance"
      | "getVerificationResult"
      | "hasBalance"
      | "protocolId"
      | "setBalance"
      | "verifySpending"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BalanceSet" | "VerificationPerformed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBalance",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySpending",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySpending",
    data: BytesLike
  ): Result;
}

export namespace BalanceSetEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationPerformedEvent {
  export type InputTuple = [
    user: AddressLike,
    allowed: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, allowed: boolean, timestamp: bigint];
  export interface OutputObject {
    user: string;
    allowed: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedBalanceVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedBalanceVerifier;
  waitForDeployment(): Promise<this>;

  interface: EncryptedBalanceVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBalance: TypedContractMethod<[user: AddressLike], [string], "view">;

  getVerificationResult: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  hasBalance: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setBalance: TypedContractMethod<
    [encryptedBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  verifySpending: TypedContractMethod<
    [encryptedSpending: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVerificationResult"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasBalance"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBalance"
  ): TypedContractMethod<
    [encryptedBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifySpending"
  ): TypedContractMethod<
    [encryptedSpending: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "BalanceSet"
  ): TypedContractEvent<
    BalanceSetEvent.InputTuple,
    BalanceSetEvent.OutputTuple,
    BalanceSetEvent.OutputObject
  >;
  getEvent(
    key: "VerificationPerformed"
  ): TypedContractEvent<
    VerificationPerformedEvent.InputTuple,
    VerificationPerformedEvent.OutputTuple,
    VerificationPerformedEvent.OutputObject
  >;

  filters: {
    "BalanceSet(address,uint64)": TypedContractEvent<
      BalanceSetEvent.InputTuple,
      BalanceSetEvent.OutputTuple,
      BalanceSetEvent.OutputObject
    >;
    BalanceSet: TypedContractEvent<
      BalanceSetEvent.InputTuple,
      BalanceSetEvent.OutputTuple,
      BalanceSetEvent.OutputObject
    >;

    "VerificationPerformed(address,bool,uint64)": TypedContractEvent<
      VerificationPerformedEvent.InputTuple,
      VerificationPerformedEvent.OutputTuple,
      VerificationPerformedEvent.OutputObject
    >;
    VerificationPerformed: TypedContractEvent<
      VerificationPerformedEvent.InputTuple,
      VerificationPerformedEvent.OutputTuple,
      VerificationPerformedEvent.OutputObject
    >;
  };
}
